export enum ActivityStatus {
  DRAFT = 'DRAFT',
  QUEUED = 'QUEUED',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  PAUSED = 'PAUSED',
  DETACHED = 'DETACHED',
  INTERRUPTED = 'INTERRUPTED',
  RECOVERABLE = 'RECOVERABLE',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}

export enum EventType {
  SESSION_STARTED = 'SESSION_STARTED',
  PROMPT_RECEIVED = 'PROMPT_RECEIVED',
  ASSISTANT_MESSAGE = 'ASSISTANT_MESSAGE',
  TOOL_STARTED = 'TOOL_STARTED',
  TOOL_COMPLETED = 'TOOL_COMPLETED',
  FILE_CHANGED = 'FILE_CHANGED',
  COMMAND_STARTED = 'COMMAND_STARTED',
  COMMAND_COMPLETED = 'COMMAND_COMPLETED',
  TEST_STARTED = 'TEST_STARTED',
  TEST_COMPLETED = 'TEST_COMPLETED',
  BUILD_STARTED = 'BUILD_STARTED',
  BUILD_COMPLETED = 'BUILD_COMPLETED',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  APPROVAL_RESOLVED = 'APPROVAL_RESOLVED',
  CHECKPOINT_CREATED = 'CHECKPOINT_CREATED',
  HANDOFF_UPDATED = 'HANDOFF_UPDATED',
  ACTIVITY_PAUSED = 'ACTIVITY_PAUSED',
  ACTIVITY_RESUMED = 'ACTIVITY_RESUMED',
  ACTIVITY_INTERRUPTED = 'ACTIVITY_INTERRUPTED',
  ACTIVITY_RECOVERED = 'ACTIVITY_RECOVERED',
  ACTIVITY_FAILED = 'ACTIVITY_FAILED',
  ACTIVITY_COMPLETED = 'ACTIVITY_COMPLETED',
}

export enum RiskLevel {
  SAFE = 'SAFE',
  CONFIRM = 'CONFIRM',
  STRONG_CONFIRM = 'STRONG_CONFIRM',
}

export enum HealthStatus {
  HEALTHY = 'HEALTHY',     // GREEN
  DEGRADED = 'DEGRADED',   // YELLOW
  UNAVAILABLE = 'UNAVAILABLE', // RED
  UNKNOWN = 'UNKNOWN',     // BLUE/GRAY
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
