/**
 * @license Apache-2.0
 * Verified Reference AI Models & Aliases
 * Data Origin: VERIFIED_REFERENCE
 * These are official reference models for Claude Code & AI Studio.
 * Unconnected models must NEVER be presented as HEALTHY, ACTIVE, or CONNECTED.
 */
import { ModelProfile } from '../models/index.ts';

export const VERIFIED_REFERENCE_MODELS: ModelProfile[] = [
  {
    schemaVersion: 1,
    id: 'ref-claude-fable-5-1',
    provider: 'Anthropic',
    displayName: 'Claude Fable 5.1',
    alias: 'fable',
    modelId: 'claude-fable-5-1',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'Official Anthropic frontier model for complex reasoning and creative engineering.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 200000,
    priority: 1,
  },
  {
    schemaVersion: 1,
    id: 'ref-claude-opus-5-5',
    provider: 'Anthropic',
    displayName: 'Claude Opus 5.5',
    alias: 'opus',
    modelId: 'claude-opus-5-5',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'Top-tier Anthropic intelligence for deep agentic coding, computer use, and architectural analysis.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 200000,
    priority: 2,
  },
  {
    schemaVersion: 1,
    id: 'ref-claude-sonnet-5-5',
    provider: 'Anthropic',
    displayName: 'Claude Sonnet 5.5',
    alias: 'sonnet',
    modelId: 'claude-sonnet-5-5',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'High-speed professional workhorse model balanced for day-to-day software development tasks.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 200000,
    priority: 3,
  },
  {
    schemaVersion: 1,
    id: 'ref-claude-haiku-4-5',
    provider: 'Anthropic',
    displayName: 'Claude Haiku 4.5',
    alias: 'haiku',
    modelId: 'claude-haiku-4-5',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'Ultra-low latency model engineered for high-volume automated tooling, linting, and rapid search.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: false,
    contextWindow: 200000,
    priority: 4,
  },
  {
    schemaVersion: 1,
    id: 'ref-claude-alias-best',
    provider: 'Anthropic',
    displayName: 'Claude Best (Alias)',
    alias: 'best',
    modelId: 'claude-opus-5-5',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'Claude Code dynamic alias resolving to highest intelligence available model on provider account.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 200000,
    priority: 5,
  },
  {
    schemaVersion: 1,
    id: 'ref-claude-alias-opusplan',
    provider: 'Anthropic',
    displayName: 'Claude Opus Plan (Alias)',
    alias: 'opusplan',
    modelId: 'claude-opus-5-5',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'Claude Code plan mode alias for architectural roadmap generation.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 200000,
    priority: 6,
  },
  {
    schemaVersion: 1,
    id: 'ref-claude-sonnet-1m',
    provider: 'Anthropic',
    displayName: 'Claude Sonnet 5.5 [1M Context]',
    alias: 'sonnet[1m]',
    modelId: 'claude-sonnet-5-5',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'Extended 1,000,000 token context window variant for whole-codebase repository analysis.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 1000000,
    priority: 7,
  },
  {
    schemaVersion: 1,
    id: 'ref-claude-opus-1m',
    provider: 'Anthropic',
    displayName: 'Claude Opus 5.5 [1M Context]',
    alias: 'opus[1m]',
    modelId: 'claude-opus-5-5',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://docs.claude.com/en/api/overview',
    notes: 'Extended 1,000,000 token context window variant for complex multi-repo synthesis.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 1000000,
    priority: 8,
  },
  {
    schemaVersion: 1,
    id: 'ref-gemini-3-8-flash',
    provider: 'Google',
    displayName: 'Gemini 3.8 Flash',
    alias: 'flash',
    modelId: 'gemini-3.8-flash',
    status: 'REFERENCE_ONLY',
    origin: 'VERIFIED_REFERENCE',
    verifiedAt: '2026-10-07T00:00:00Z',
    sourceUrl: 'https://ai.google.dev',
    notes: 'Current verified Google model in AI Studio runtime. Reference data only.',
    toolCalling: true,
    streaming: true,
    thinkingSupport: true,
    contextWindow: 1000000,
    priority: 9,
  },
];
